version: '3'
services:
  app:
    image: node:alpine
    volumes:
      - .:/app
    working_dir: /app
    environment:
     - GROWI_APP_SITE_URL=${GROWI_APP_SITE_URL}
     - GROWI_ACCESS_TOKEN=${GROWI_ACCESS_TOKEN}
     - POCKET_CONSUMER_KEY=${POCKET_CONSUMER_KEY}
     - POCKET_REQUEST_TOKEN=${POCKET_REQUEST_TOKEN}
     - POCKET_ACCESS_TOKEN=${POCKET_ACCESS_TOKEN}
